### ISSUE TITLE
I can't list orders anymore, error: 'Value cannot be null. Parameter name: source'

### ISSUE THREAD

**Issue by danicodeRO** [Bukimedia/PrestaSharp#405]
**Library Version:**

1.1.0
RestSharp: 106.11.4

**Prestashop version:**
 
1.6.1.23
 
**Describe the Bug:**

When I tried to download the orders, now I get the error:

System.ArgumentNullException: 'Value cannot be null.
Parameter name: source'

**To Reproduce:**
The code on the guide, my code is in Vb.Net. It worked, but I think is because of updates.

           Dim mag As Magazin = f.Magazinul(IdMagazin)

            Dim p As New ManufacturerFactory(mag.Adresa, mag.parola, "")
            Dim o As New OrderFactory(mag.Adresa, mag.parola, "")

            Dim filter As Dictionary(Of String, String) = New Dictionary(Of String, String)()
            Dim dFrom As String = String.Format("{0:yyyy-MM-dd HH:mm:ss}", dataInceput)
            Dim dTo As String = String.Format("{0:yyyy-MM-dd HH:mm:ss}", dataSfarsit)
            filter.Add("date_add", "[" & dFrom & "," & dTo & "]")
            Dim PrestaSharpOrderIds As List(Of Long) = o.GetIdsByFilter(filter, "id_DESC", Nothing)

Stack trace:
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Bukimedia.PrestaSharp.Factories.GenericFactory`1.GetIdsByFilter(Dictionary`2 Filter, String Sort, String Limit)
   at Gestiune.PrestaShop.verificaComenzi(String user, String parola, Int32 IdMagazin, DateTime dataInceput, DateTime dataSfarsit)

**Comment by danicodeRO** [comment]
I have downloaded the source code, and the error is here:

![image](https://user-images.githubusercontent.com/23075607/88478740-64e22980-cf53-11ea-98b7-634ec678e5f3.png)

   at Bukimedia.PrestaSharp.Deserializers.PrestaSharpDeserializer.CreateAndMap(Type t, XElement element) in E:\temp\PrestaSharp-master\PrestaSharp\Deserializers\PrestaSharpDeserializer.cs:line 378
   at Bukimedia.PrestaSharp.Deserializers.PrestaSharpDeserializer.PopulateListFromElements(Type t, IEnumerable`1 elements, IList list) in E:\temp\PrestaSharp-master\PrestaSharp\Deserializers\PrestaSharpDeserializer.cs:line 282

**Comment by danicodeRO** [comment]
I have installed PrestaSharp.Extended and it fixed the errors. Hope it helps others..
